# Generated by Django 3.2.6 on 2021-08-21 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publicated_at', models.DateTimeField(blank=True, null=True)),
                ('moderated_at', models.BooleanField(default=False)),
                ('picture', models.ImageField(blank=True, upload_to='pictures', verbose_name='Картинки')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок объявления')),
                ('text', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Текст объявления')),
                ('category', models.CharField(choices=[('Computers', 'Компьютеры'), ('Cars', 'Автомобили'), ('Other', 'Другое')], max_length=300)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advert', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
